create table if not exists public.app_status (
  id bigint generated by default as identity primary key,
  name text not null unique,
  value text not null,
  updated_at timestamptz not null default now()
);

insert into public.app_status (name, value)
values ('backend', 'supabase-ready')
on conflict (name)
do update set
  value = excluded.value,
  updated_at = now();

alter table public.app_status enable row level security;

drop policy if exists "Public read access to app status" on public.app_status;

create policy "Public read access to app status"
on public.app_status
for select
using (true);