create extension if not exists "pgcrypto";

do $$
begin
  if not exists (select 1 from pg_type where typname = 'contractor_status') then
    create type public.contractor_status as enum (
      'invited',
      'kyc_pending',
      'kyc_complete',
      'agreement_signed',
      'active',
      'paused'
    );
  end if;
end$$;

do $$3
begin
  if not exists (select 1 from pg_type where typname = 'invoice_status') then
    create type public.invoice_status as enum ('created', 'paid', 'disputed');
  end if;
end$$;

do $$
begin
  if not exists (select 1 from pg_type where typname = 'attestation_type') then
    create type public.attestation_type as enum ('identity', 'agreement', 'payment');
  end if;
end$$;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.businesses (
  id uuid primary key default gen_random_uuid(),
  user_id uuid unique references auth.users(id) on delete set null,
  name text not null,
  wallet_address text unique,
  chain_id bigint not null default 43113,
  created_at timestamptz not null default now()
);

create table if not exists public.contractors (
  id uuid primary key default gen_random_uuid(),
  business_id uuid not null references public.businesses(id) on delete cascade,
  name text not null,
  email text not null,
  hourly_rate numeric(10,2) not null check (hourly_rate >= 0),
  contract_terms text not null default 'standard',
  wallet_address text,
  preferred_chain_id bigint default 43113,
  preferred_token text default 'dNZD',
  status public.contractor_status not null default 'invited',
  civic_pass_id text,
  invite_token uuid not null default gen_random_uuid(),
  gst_registered boolean not null default false,
  ir330c_uploaded boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.invoices (
  id uuid primary key default gen_random_uuid(),
  onchain_id bigint,
  business_id uuid not null references public.businesses(id) on delete cascade,
  contractor_id uuid not null references public.contractors(id) on delete cascade,
  amount numeric(10,2) not null check (amount >= 0),
  gst_amount numeric(10,2) not null default 0 check (gst_amount >= 0),
  token_symbol text not null default 'dNZD',
  chain_id bigint not null default 43113,
  description text,
  status public.invoice_status not null default 'created',
  invoice_tx_hash text,
  tx_hash text,
  created_at timestamptz not null default now(),
  paid_at timestamptz,
  unique (chain_id, onchain_id)
);

create table if not exists public.attestations (
  id uuid primary key default gen_random_uuid(),
  contractor_id uuid not null references public.contractors(id) on delete cascade,
  attestation_uid text not null unique,
  schema_uid text,
  attestation_type public.attestation_type not null,
  document_hash text,
  tx_hash text,
  chain_id bigint not null default 43113,
  created_at timestamptz not null default now()
);

create table if not exists public.app_status (
  id bigint generated by default as identity primary key,
  name text not null unique,
  value text not null,
  updated_at timestamptz not null default now()
);

drop trigger if exists trg_contractors_updated_at on public.contractors;
create trigger trg_contractors_updated_at
before update on public.contractors
for each row execute function public.set_updated_at();

create index if not exists idx_businesses_user_id on public.businesses(user_id);
create index if not exists idx_contractors_business_id on public.contractors(business_id);
create index if not exists idx_contractors_invite_token on public.contractors(invite_token);
create index if not exists idx_invoices_business_id on public.invoices(business_id);
create index if not exists idx_invoices_contractor_id on public.invoices(contractor_id);
create index if not exists idx_attestations_contractor_id on public.attestations(contractor_id);

alter table public.businesses enable row level security;
alter table public.contractors enable row level security;
alter table public.invoices enable row level security;
alter table public.attestations enable row level security;
alter table public.app_status enable row level security;

drop policy if exists "Business sees own record" on public.businesses;
create policy "Business sees own record"
on public.businesses
for all
using (auth.role() = 'service_role' or user_id = auth.uid())
with check (auth.role() = 'service_role' or user_id = auth.uid());

drop policy if exists "Business sees own contractors" on public.contractors;
create policy "Business sees own contractors"
on public.contractors
for all
using (
  auth.role() = 'service_role'
  or business_id in (select b.id from public.businesses b where b.user_id = auth.uid())
)
with check (
  auth.role() = 'service_role'
  or business_id in (select b.id from public.businesses b where b.user_id = auth.uid())
);

drop policy if exists "Business sees own invoices" on public.invoices;
create policy "Business sees own invoices"
on public.invoices
for all
using (
  auth.role() = 'service_role'
  or business_id in (select b.id from public.businesses b where b.user_id = auth.uid())
)
with check (
  auth.role() = 'service_role'
  or business_id in (select b.id from public.businesses b where b.user_id = auth.uid())
);

drop policy if exists "Business sees own attestations" on public.attestations;
create policy "Business sees own attestations"
on public.attestations
for all
using (
  auth.role() = 'service_role'
  or contractor_id in (
    select c.id
    from public.contractors c
    where c.business_id in (select b.id from public.businesses b where b.user_id = auth.uid())
  )
)
with check (
  auth.role() = 'service_role'
  or contractor_id in (
    select c.id
    from public.contractors c
    where c.business_id in (select b.id from public.businesses b where b.user_id = auth.uid())
  )
);

drop policy if exists "Public read access to app status" on public.app_status;
create policy "Public read access to app status"
on public.app_status
for select
using (true);

insert into public.businesses (id, name, wallet_address, chain_id)
values (
  '10000000-0000-0000-0000-000000000001',
  'Kiwi Electrical Limited',
  '0xB1ZN355000000000000000000000000000001',
  43113
)
on conflict (id) do nothing;

insert into public.contractors (
  id,
  business_id,
  name,
  email,
  hourly_rate,
  contract_terms,
  wallet_address,
  preferred_chain_id,
  preferred_token,
  status,
  gst_registered
)
values (
  '20000000-0000-0000-0000-000000000001',
  '10000000-0000-0000-0000-000000000001',
  'Sarah Electrician',
  'sarah@email.co.nz',
  80.00,
  'standard',
  '0xC0N7RAC7000000000000000000000000000001',
  43113,
  'dNZD',
  'agreement_signed',
  true
)
on conflict (id) do nothing;

insert into public.invoices (
  id,
  onchain_id,
  business_id,
  contractor_id,
  amount,
  gst_amount,
  token_symbol,
  chain_id,
  description,
  status
)
values (
  '30000000-0000-0000-0000-000000000001',
  1,
  '10000000-0000-0000-0000-000000000001',
  '20000000-0000-0000-0000-000000000001',
  800.00,
  120.00,
  'dNZD',
  43113,
  'Weekly electrical maintenance (10 hours)',
  'created'
)
on conflict (id) do nothing;

insert into public.attestations (
  id,
  contractor_id,
  attestation_uid,
  schema_uid,
  attestation_type,
  document_hash,
  chain_id
)
values (
  '40000000-0000-0000-0000-000000000001',
  '20000000-0000-0000-0000-000000000001',
  '0xattestationuiddemo000000000000000000000000000000000000000000000001',
  '0xschemauiddemo000000000000000000000000000000000000000000000000000001',
  'agreement',
  '0xdoc0000000000000000000000000000000000000000000000000000000000001',
  43113
)
on conflict (id) do nothing;

insert into public.app_status (name, value)
values ('backend', 'supabase-ready')
on conflict (name)
do update set
  value = excluded.value,
  updated_at = now();